export const SET_CURRENT_ADDRESS = 'SET_CURRENT_ADDRESS';
export const GET_ACCOUNT_ADDRESSES = 'GET_ACCOUNT_ADDRESSES';
export const GET_USER_VOTED_EVENTS_BY_ACCOUNT = 'GET_USER_VOTED_EVENTS_BY_ACCOUNT';
export const GET_HOST_EVENT_STATUS = 'GET_EVENT_STATUS';



